export const ingredientDB = {
  "glycerin": { acne_safe: true, irritation: 0, hydration: 10, oil_control: 0 },
  "niacinamide": { acne_safe: true, irritation: 1, hydration: 4, oil_control: 8 },
  "salicylic acid": { acne_safe: true, irritation: 6, hydration: 0, oil_control: 10 },
  "fragrance": { acne_safe: false, irritation: 8, hydration: 0, oil_control: 0 },
  "alcohol": { acne_safe: false, irritation: 7, hydration: 0, oil_control: 5 },
  "hyaluronic acid": { acne_safe: true, irritation: 0, hydration: 10, oil_control: 0 },
  "vitamin c": { acne_safe: true, irritation: 5, hydration: 1, oil_control: 0 },
  "retinol": { acne_safe: true, irritation: 8, hydration: 0, oil_control: 3 },
  "retinoids": { acne_safe: true, irritation: 9, hydration: 0, oil_control: 4 },
  "ceramides": { acne_safe: true, irritation: 0, hydration: 8, oil_control: 0 },
  "glycolic acid": { acne_safe: true, irritation: 7, hydration: 2, oil_control: 4 },
  "green tea extract": { acne_safe: true, irritation: 0, hydration: 3, oil_control: 6 },
  "squalane": { acne_safe: true, irritation: 0, hydration: 8, oil_control: 2 },
  "bakuchiol": { acne_safe: true, irritation: 1, hydration: 2, oil_control: 2 },
  "hydroquinone": { acne_safe: true, irritation: 6, hydration: 0, oil_control: 0 },
  "propylene glycol": { acne_safe: true, irritation: 2, hydration: 5, oil_control: 0 },
  "butylene glycol": { acne_safe: true, irritation: 1, hydration: 5, oil_control: 0 },
  "sodium pca": { acne_safe: true, irritation: 0, hydration: 8, oil_control: 0 },
  "panthenol": { acne_safe: true, irritation: 0, hydration: 7, oil_control: 0 },
  "urea": { acne_safe: true, irritation: 2, hydration: 9, oil_control: 0 },
  "trehalose": { acne_safe: true, irritation: 0, hydration: 8, oil_control: 0 },
  "betaine": { acne_safe: true, irritation: 0, hydration: 7, oil_control: 0 },
  "sorbitol": { acne_safe: true, irritation: 0, hydration: 6, oil_control: 0 },
  "allantoin": { acne_safe: true, irritation: 0, hydration: 4, oil_control: 0 },
  "sodium lactate": { acne_safe: true, irritation: 1, hydration: 7, oil_control: 0 },
  "shea butter": { acne_safe: false, irritation: 0, hydration: 10, oil_control: 0 },
  "cocoa butter": { acne_safe: false, irritation: 0, hydration: 9, oil_control: 0 },
  "jojoba oil": { acne_safe: true, irritation: 0, hydration: 8, oil_control: 2 },
  "argan oil": { acne_safe: true, irritation: 0, hydration: 7, oil_control: 1 },
  "rosehip oil": { acne_safe: true, irritation: 0, hydration: 6, oil_control: 1 },
  "almond oil": { acne_safe: false, irritation: 1, hydration: 7, oil_control: 0 },
  "coconut oil": { acne_safe: false, irritation: 1, hydration: 9, oil_control: 0 },
  "olive oil": { acne_safe: false, irritation: 1, hydration: 8, oil_control: 0 },
  "sunflower seed oil": { acne_safe: true, irritation: 0, hydration: 7, oil_control: 0 },
  "grapeseed oil": { acne_safe: true, irritation: 0, hydration: 6, oil_control: 1 },
  "lactic acid": { acne_safe: true, irritation: 4, hydration: 5, oil_control: 3 },
  "mandelic acid": { acne_safe: true, irritation: 3, hydration: 2, oil_control: 5 },
  "azelaic acid": { acne_safe: true, irritation: 3, hydration: 0, oil_control: 8 },
  "citric acid": { acne_safe: true, irritation: 4, hydration: 0, oil_control: 3 },
  "malic acid": { acne_safe: true, irritation: 4, hydration: 2, oil_control: 2 },
  "tartaric acid": { acne_safe: true, irritation: 4, hydration: 1, oil_control: 2 },
  "polyhydroxy acid (pha)": { acne_safe: true, irritation: 1, hydration: 6, oil_control: 2 },
  "gluconolactone": { acne_safe: true, irritation: 1, hydration: 6, oil_control: 2 },
  "lactobionic acid": { acne_safe: true, irritation: 1, hydration: 7, oil_control: 1 },
  "ferulic acid": { acne_safe: true, irritation: 2, hydration: 0, oil_control: 0 },
  "alpha arbutin": { acne_safe: true, irritation: 1, hydration: 0, oil_control: 0 },
  "kojic acid": { acne_safe: true, irritation: 4, hydration: 0, oil_control: 0 },
  "tranexamic acid": { acne_safe: true, irritation: 1, hydration: 0, oil_control: 0 },
  "licorice root extract": { acne_safe: true, irritation: 0, hydration: 2, oil_control: 3 },
  "mulberry extract": { acne_safe: true, irritation: 0, hydration: 1, oil_control: 0 },
  "bearberry extract": { acne_safe: true, irritation: 0, hydration: 1, oil_control: 0 },
  "glutathione": { acne_safe: true, irritation: 0, hydration: 1, oil_control: 0 },
  "resorcinol": { acne_safe: true, irritation: 7, hydration: 0, oil_control: 4 },
  "cysteamine": { acne_safe: true, irritation: 4, hydration: 0, oil_control: 0 },
  "ellagic acid": { acne_safe: true, irritation: 1, hydration: 0, oil_control: 0 },
  "aloe vera": { acne_safe: true, irritation: 0, hydration: 8, oil_control: 0 },
  "centella asiatica": { acne_safe: true, irritation: 0, hydration: 6, oil_control: 1 },
  "chamomile extract": { acne_safe: true, irritation: 0, hydration: 4, oil_control: 0 },
  "calendula extract": { acne_safe: true, irritation: 0, hydration: 4, oil_control: 0 },
  "oat extract": { acne_safe: true, irritation: 0, hydration: 7, oil_control: 0 },
  "madecassoside": { acne_safe: true, irritation: 0, hydration: 5, oil_control: 0 },
  "bisabolol": { acne_safe: true, irritation: 0, hydration: 3, oil_control: 0 },
  "cica extract": { acne_safe: true, irritation: 0, hydration: 6, oil_control: 0 },
  "mugwort extract": { acne_safe: true, irritation: 0, hydration: 4, oil_control: 2 },
  "turmeric extract": { acne_safe: true, irritation: 1, hydration: 2, oil_control: 3 },
  "vitamin e (tocopherol)": { acne_safe: true, irritation: 1, hydration: 6, oil_control: 0 },
  "coenzyme q10": { acne_safe: true, irritation: 0, hydration: 2, oil_control: 0 },
  "resveratrol": { acne_safe: true, irritation: 0, hydration: 2, oil_control: 0 },
  "astaxanthin": { acne_safe: true, irritation: 0, hydration: 3, oil_control: 0 },
  "idebenone": { acne_safe: true, irritation: 2, hydration: 1, oil_control: 0 },
  "beta carotene": { acne_safe: true, irritation: 0, hydration: 2, oil_control: 0 },
  "polyphenols": { acne_safe: true, irritation: 0, hydration: 2, oil_control: 0 },
  "superoxide dismutase": { acne_safe: true, irritation: 0, hydration: 2, oil_control: 0 },
  "copper peptides": { acne_safe: true, irritation: 1, hydration: 4, oil_control: 0 },
  "cholesterol": { acne_safe: true, irritation: 0, hydration: 7, oil_control: 0 },
  "fatty acids": { acne_safe: false, irritation: 0, hydration: 8, oil_control: 0 },
  "phytosphingosine": { acne_safe: true, irritation: 0, hydration: 6, oil_control: 1 },
  "lecithin": { acne_safe: true, irritation: 0, hydration: 6, oil_control: 0 },
  "hydrogenated lecithin": { acne_safe: true, irritation: 0, hydration: 6, oil_control: 0 },
  "zinc oxide": { acne_safe: true, irritation: 0, hydration: 0, oil_control: 5 },
  "titanium dioxide": { acne_safe: true, irritation: 0, hydration: 0, oil_control: 3 },
  "avobenzone": { acne_safe: true, irritation: 3, hydration: 0, oil_control: 0 },
  "octinoxate": { acne_safe: true, irritation: 2, hydration: 0, oil_control: 0 },
  "octocrylene": { acne_safe: true, irritation: 2, hydration: 0, oil_control: 0 },
  "homosalate": { acne_safe: true, irritation: 2, hydration: 0, oil_control: 0 },
  "oxybenzone": { acne_safe: true, irritation: 4, hydration: 0, oil_control: 0 },
  "phenoxyethanol": { acne_safe: true, irritation: 2, hydration: 0, oil_control: 0 },
  "parabens": { acne_safe: true, irritation: 1, hydration: 0, oil_control: 0 },
  "ethylhexylglycerin": { acne_safe: true, irritation: 1, hydration: 2, oil_control: 0 },
  "benzyl alcohol": { acne_safe: false, irritation: 4, hydration: 0, oil_control: 1 },
  "potassium sorbate": { acne_safe: true, irritation: 2, hydration: 0, oil_control: 0 },
  "sodium benzoate": { acne_safe: true, irritation: 2, hydration: 0, oil_control: 0 },
  "chlorphenesin": { acne_safe: true, irritation: 2, hydration: 0, oil_control: 0 },
  "sodium lauryl sulfate (sls)": { acne_safe: false, irritation: 9, hydration: 0, oil_control: 8 },
  "sodium laureth sulfate (sles)": { acne_safe: false, irritation: 6, hydration: 0, oil_control: 6 },
  "cocamidopropyl betaine": { acne_safe: true, irritation: 3, hydration: 2, oil_control: 4 },
  "decyl glucoside": { acne_safe: true, irritation: 1, hydration: 4, oil_control: 3 },
  "dimethicone": { acne_safe: true, irritation: 0, hydration: 4, oil_control: 0 },
  "carbomer": { acne_safe: true, irritation: 0, hydration: 2, oil_control: 0 }
};

export const queryKnowledgeBase = async (ingredient) => {
  return ingredientDB[ingredient.toLowerCase()] || null;
};
